### ISSUE TITLE
Now that smart search is deprecated, what is the replacement?

### ISSUE THREAD

**Issue by NateAtBV** [nuxeo/nuxeo-platform-smart-search#3]
Sorry that this isn't a proper issue, but I can't find an answer anywhere else.

**Comment by efge** [comment]
Please ask questions on https://answers.nuxeo.com/

**Comment by NateAtBV** [comment]
I realize this isn't the forum for questions like mine, but there has been
no response on answers.nuxeo.com for days.  We rely on this functionality
in our product and nobody is saying anything!  Just that it's deprecated.
No explanation, no replacement.  You're the only response I've received on
any forum anywhere.

Sorry I have to go outside the rules here.

Nate


Nate Jones
Senior Software Engineer
www.baseventure.com

**Comment by efge** [comment]
Please keep pinging answers.nuxeo.com.
